# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV["VAGRANT_EXPERIMENTAL"] = "disks"

$URL_MIRROR_LUSTRE = ENV["URL_MIRROR_LUSTRE"] || \
"https://downloads.whamcloud.com/public"

hosts = %q(
127.0.0.1     localhost localhost.localdomain localhost4 localhost4.localdomain4
::1           localhost localhost.localdomain localhost6 localhost6.localdomain6

192.168.10.10 mxs
192.168.10.20 oss
192.168.10.30 client
)

$create_file_hosts = <<-SCRIPT
echo "#{hosts}" > /etc/hosts
SCRIPT

$create_repo_e2fsprogs = <<-SCRIPT
cat > /etc/yum.repos.d/e2fsprogs-wc.repo <<EOF
[e2fsprogs-wc]
name=e2fsprogs-wc
baseurl=#{$URL_MIRROR_LUSTRE}/e2fsprogs/latest/el7
gpgcheck=0
enabled=0
EOF
SCRIPT

$create_repo_lustre_server = <<-SCRIPT
cat > /etc/yum.repos.d/lustre-server.repo <<EOF
[lustre-server]
name=lustre-server
baseurl=#{$URL_MIRROR_LUSTRE}/lustre/lustre-2.12.5/el7.8.2003/server
gpgcheck=0
enabled=0
EOF
SCRIPT

$create_repo_lustre_client = <<-SCRIPT
cat > /etc/yum.repos.d/lustre-client.repo <<EOF
[lustre-client]
name=lustre-client
baseurl=#{$URL_MIRROR_LUSTRE}/lustre/lustre-2.12.5/el7.8.2003/client
gpgcheck=0
enabled=0
EOF
SCRIPT

$install_packages_e2fsprogs = <<-SCRIPT
yum install -y --nogpgcheck --disablerepo=* --enablerepo=e2fsprogs-wc e2fsprogs
SCRIPT

$install_packages_dkms = <<-SCRIPT
yum list installed | grep -E "^dkms.*2\.7\.1.*"
exitCode=$?
if [ $exitCode -ne 0 ]; then
    yum install -y https://download-ib01.fedoraproject.org/pub/epel/7/aarch64/Packages/d/dkms-2.7.1-1.el7.noarch.rpm
else
    echo "Skipping installation of package dkms, since it is already installed."
fi
SCRIPT

$remove_packages_kernel_tools = <<-SCRIPT
yum remove -y kernel-tools
yum remove -y kernel-tools-libs
SCRIPT

$remove_old_kernel = <<-SCRIPT
yum remove -y kernel-3.10.0-1127.el7
SCRIPT

$install_packages_kernel_patched = <<-SCRIPT
yum --nogpgcheck --disablerepo=* --enablerepo=lustre-server install -y \
kernel \
kernel-devel \
kernel-headers \
kernel-tools \
kernel-tools-libs \
kernel-tools-libs-devel
SCRIPT

$install_packages_server_ldiskfs = <<-SCRIPT
yum --nogpgcheck --enablerepo=lustre-server install -y \
lustre-osd-ldiskfs-mount \
lustre
SCRIPT

$install_packages_server_zfs = <<-SCRIPT
yum --nogpgcheck --enablerepo=lustre-server install -y \
lustre-dkms \
lustre-osd-zfs-mount \
lustre \
zfs
SCRIPT

$install_packages_client = <<-SCRIPT
yum --nogpgcheck --enablerepo=lustre-client install -y \
kmod-lustre-client \
lustre-client
SCRIPT

$configure_lnet = <<-SCRIPT
# Should be set before lnet module is loaded.
echo "options lnet networks=tcp0(eth1)" > /etc/modprobe.d/lnet.conf
SCRIPT

$configure_lustre_server_mgs_mds = <<-SCRIPT
disk_types="sd vd UNKNOWN"
for disk_type in $disk_types; do
  if [ -b "/dev/${disk_type}b" ]; then
    break
  fi
done
modprobe -v lnet
modprobe -v lustre
mkdir /mnt/mdt
mkfs.lustre --backfstype=ldiskfs --fsname=phoenix --mgs --mdt --index=0 /dev/${disk_type}b
mount -t lustre /dev/${disk_type}b /mnt/mdt
SCRIPT

$configure_lustre_server_oss_zfs = <<-SCRIPT
disk_types="sd vd UNKNOWN"
for disk_type in $disk_types; do
  if [ -b "/dev/${disk_type}b" ]; then
    break
  fi
done
modprobe -v lnet
modprobe -v lustre
modprobe -v zfs
zpool create ostpool0 /dev/${disk_type}b
zpool create ostpool1 /dev/${disk_type}c
mkfs.lustre --backfstype=zfs --ost --fsname phoenix --index 0 --mgsnode mxs@tcp0 ostpool0/ost0
mkfs.lustre --backfstype=zfs --ost --fsname phoenix --index 1 --mgsnode mxs@tcp0 ostpool1/ost1
mkdir -p /lustre/phoenix/ost0
mkdir -p /lustre/phoenix/ost1
mount -t lustre ostpool0/ost0 /lustre/phoenix/ost0
mount -t lustre ostpool1/ost1 /lustre/phoenix/ost1
SCRIPT

$configure_lustre_client = <<-SCRIPT
mkdir /lustre
mount -t lustre mxs@tcp0:/phoenix /lustre
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 2
  end
  config.vm.provider :libvirt

  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01" # CentOS 7.8.2003
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", name: "create_file_hosts", inline: $create_file_hosts

  config.vm.define  "mxs" do |mxs|
    mxs.vm.hostname = "mxs"
    mxs.vm.network "private_network", ip: "192.168.10.10"
    mxs.vm.provider :virtualbox do |vbox|
      vbox.disk :disk, size: "10GB", name: "disk_for_lustre"
    end
    mxs.vm.provider :libvirt do |libvirt|
      libvirt.storage :file,
                      :path => 'disk_for_lustre.img',
                      :size => '10G',
                      :type => 'raw'
    end
    mxs.vm.provision "shell", name: "create_repo_e2fsprogs", inline: $create_repo_e2fsprogs
    mxs.vm.provision "shell", name: "create_repo_lustre_server", inline: $create_repo_lustre_server
    mxs.vm.provision "shell", name: "remove_packages_kernel_tools", inline: $remove_packages_kernel_tools
    mxs.vm.provision "shell", name: "install_perl", inline: "yum install -y perl"
    mxs.vm.provision "shell", name: "install_packages_kernel", inline: $install_packages_kernel_patched, reboot: true
    mxs.vm.provision "shell", name: "remove_old_kernel", inline: $remove_old_kernel
    mxs.vm.provision "shell", name: "install_packages_e2fsprogs", inline: $install_packages_e2fsprogs
    mxs.vm.provision "shell", name: "install_packages_ldiskfs", inline: $install_packages_server_ldiskfs
    mxs.vm.provision "shell", name: "configure_lnet", inline: $configure_lnet
    mxs.vm.provision "shell", name: "configure_mgs_mds", inline: $configure_lustre_server_mgs_mds
  end

  config.vm.define  "oss" do |oss|
    oss.vm.hostname = "oss"
    oss.vm.network "private_network", ip: "192.168.10.20"
    oss.vm.provider :virtualbox do |vbox|
      oss.vm.disk :disk, size: "10GB", name: "disk_for_lustre_ost_1"
      oss.vm.disk :disk, size: "10GB", name: "disk_for_lustre_ost_2"
    end
    oss.vm.provider :libvirt do |libvirt|
      libvirt.storage :file,
                      :path => 'disk_for_lustre_ost_1.img',
                      :size => '10G',
                      :type => 'raw'
      libvirt.storage :file,
                      :path => 'disk_for_lustre_ost_2.img',
                      :size => '10G',
                      :type => 'raw'
    end
    oss.vm.provision "shell", name: "create_repo_e2fsprogs", inline: $create_repo_e2fsprogs
    oss.vm.provision "shell", name: "create_repo_lustre_server", inline: $create_repo_lustre_server
    oss.vm.provision "shell", name: "remove_packages_kernel_tools", inline: $remove_packages_kernel_tools
    oss.vm.provision "shell", name: "install_perl", inline: "yum install -y perl"
    oss.vm.provision "shell", name: "install_packages_kernel_patched", inline: $install_packages_kernel_patched, reboot: true
    oss.vm.provision "shell", name: "remove_old_kernel", inline: $remove_old_kernel
    oss.vm.provision "shell", name: "install_packages_dkms", inline: $install_packages_dkms
    oss.vm.provision "shell", name: "install_packages_e2fsprogs", inline: $install_packages_e2fsprogs
    oss.vm.provision "shell", name: "install_packages_zfs", inline: $install_packages_server_zfs
    oss.vm.provision "shell", name: "configure_lnet", inline: $configure_lnet
    oss.vm.provision "shell", name: "configure_oss", inline: $configure_lustre_server_oss_zfs
  end

  config.vm.define  "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.10.30"
    client.vm.provision "shell", name: "create_repo_lustre_client", inline: $create_repo_lustre_client
    client.vm.provision "shell", name: "install_packages_client", inline: $install_packages_client
    client.vm.provision "shell", name: "configure_lnet", inline: $configure_lnet
    client.vm.provision "shell", name: "configure_client", inline: $configure_lustre_client
  end
end
